apiVersion: v1
kind: Secret
metadata:
  name: tempostack-s3
  namespace: openshift-tracing
stringData:
  forcepathstyle: "true"
  bucket: replace me
  endpoint: replace me
  access_key_id: replacement
  access_key_secret: replacement

