namespace: example-apps
resources:
  - ../../../components/rbac/service-accounts/privileged
  - ../../../components/k8s-namespace
  - ../../../apps/simple-load-tester
patches:
  - target:
      kind: Namespace
      name: patch-me
    patch: |-
      - op: replace
        path: /metadata/name
        value: example-apps
  - target:
      kind: BuildConfig
      name: simple-load-tester-web-server
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-apps
  - target:
      kind: ImageStream
      name: simple-load-tester-web-server
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-apps
  - target:
      kind: Deployment
      name: simple-load-tester-web-server
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-apps
      - op: add
        path: /spec/template/metadata/annotations
        value:
          instrumentation.opentelemetry.io/inject-go: "openshift-observability/instrumentation"
      - op: add
        path: /spec/template/spec/serviceAccount
        value: simple-load-tester-sa
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: image-registry.openshift-image-registry.svc:5000/example-apps/simple-load-tester-web-server:latest
  - target:
      kind: ConfigMap
      name: app-config
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-apps
      - op: replace
        path: /data/web_server_host
        value: simple-load-tester-web-server.example-apps
  - target:
      kind: ServiceAccount
      name: replace-me
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/name
        value: simple-load-tester-sa
      - op: replace
        path: /metadata/namespace
        value: example-apps
  - target:
      kind: ClusterRoleBinding
      name: replace-me
    patch: |-
      - op: replace
        path: /metadata/name
        value: simple-load-tester-sa-binding
      - op: replace
        path: /subjects/0/name
        value: simple-load-tester-sa
      - op: replace
        path: /subjects/0/namespace
        value: example-apps
