apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cluster-observability-operator
  namespace: openshift-operators
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: stable
  installPlanApproval: Automatic
  name: cluster-observability-operator
  startingCSV: cluster-observability-operator.v1.4.0
