resources:
- ../../../../../../components/openshift-logging/resources/loki-stack/stack
- ../../../../../../components/openshift-logging/resources/clusterlogforwarders/lokistack
patches:
  - target:
      kind: LokiStack
      name: logging-loki
      namespace: openshift-logging
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: gp3-csi
      - op: replace
        path: /spec/size
        value: 1x.pico
