apiVersion: v1
kind: Secret
metadata:
  name: replace-me
  namespace: replace-me
stringData:
  forcepathstyle: "true"
  bucketnames: replace me
  endpoint: replace me
  access_key_id: replacement
  access_key_secret: replacement
