apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  forcepathstyle: "true"
  bucketnames: replace me
  region: replace me
  endpoint: replace me
  audience: openshift
  access_key_id: replace me
  access_key_secret: replace me
