apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  managementState: Managed
  limits:
    global:
      retention:
        days: 30
  size: 1x.small
  storage:
    schemas:
      - version: v13
        effectiveDate: "2026-02-04" # needs to be set to two months before install date
    secret:
      name: logging-loki-s3
      type: s3
  storageClassName: replace-me
  tenants:
    mode: openshift-logging
