# schema: https://github.com/rhobs/observability-operator/blob/9396944589210b627697506c855a0784b33a3ebc/pkg/apis/uiplugin/v1alpha1/types.go#L41
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: monitoring
spec:
  type: Monitoring
  monitoring:
    # This enables ACM features.
    acm:
      enabled: true
      alertmanager:
        url: "https://alertmanager.open-cluster-management-observability.svc:8443"
      thanosQuerier:
        url: "https://rbac-query-proxy.open-cluster-management-observability.svc:8443"
      # enables mapping alerts to components
    clusterHealthAnalyzer:
      enabled: true

