apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: rhobs-console
  namespace: replace-me
spec:
  hostname: replace-me
  kafkaClusters:
    - name: replace-me
      namespace: replace-me
      listener: replace-me
