resources:
  - ../../../../components/openshift-otel/resources/instrumentation
patches:
  - target:
      kind: Instrumentation
      name: instrumentation
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: openshift-observability
      - op: replace
        path: /spec/exporter/endpoint
        value: http://otel-collector.openshift-observability.svc.cluster.local:4318
