---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: web-server
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: web-server
spec:
  source:
    git:
      uri: https://github.com/redhat-na-ssa/demo-cluster-observability-rhobs
      ref: refactor
    contextDir: apps/example-apps/web-server/src
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/go-toolset:1.19
  output:
    to:
      kind: ImageStreamTag
      name: web-server:latest
  triggers:
    - type: ConfigChange
# status:
#   lastVersion: 1336
