apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-server
    component: web-server
  name: web-server
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: web-server
    component: web-server
  type: ClusterIP
